package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"learn_gqlgen/graph/model"
	"learn_gqlgen/todo/entity"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	getNewTodo := &entity.NewTodo{
		Text:   input.Text,
		UserID: input.UserID,
	}
	if r.TodoService == nil {
		return nil, fmt.Errorf("Service non initié !")
	}
	res, err := r.TodoService.AddTodo(ctx, getNewTodo)
	if err != nil {
		return nil, fmt.Errorf("Erreur sur l'ajout de la Todo.")
	}
	return &model.Todo{
		ID:   res.ID,
		Text: res.Text,
		Done: res.Done,
	}, nil
}

// GetTodo is the resolver for the getTodo field.
func (r *queryResolver) GetTodo(ctx context.Context, id string) (*model.Todo, error) {
	todo, err := r.TodoService.GetTodo(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("Erreur lors de la récupération de la todo.")
	}
	return &model.Todo{
		Text: todo.Text,
		Done: todo.Done,
	}, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	var todos []*model.Todo
	allTodos, err := r.TodoService.GetAllTodos(ctx)
	if err != nil {
		return nil, fmt.Errorf("Erreur lors de la récupération des todos.")
	}
	for _, todo := range allTodos {
		thisTodo := &model.Todo{
			Text: todo.Text,
			Done: todo.Done,
		}
		todos = append(todos, thisTodo)
	}
	return todos, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
