# GraphQL schema example
#
# https://gqlgen.com/getting-started/

scalar Time

type User {
  id: ID!
  name: String!
  email: String!
  passwordHashed: String!
  createdAt: Time!
  updatedAt: Time
}

type Todo {
  id: ID!
  text: String!
  done: Boolean!
  user: User!
  createdAt: Time!
  updatedAt: Time
}

type Query {
  getTodo(id: ID!): Todo!
  todos: [Todo!]!
}

input NewUser {
  name: String!
  email: String!
  password: String!
}

input NewLogin {
  email: String!
  password: String!
}

input NewTodo {
  text: String!
  userId: String!
}

interface MutationPayload {
  message: String!
}

type CreateUserPayload implements MutationPayload {
  user: User!
  message: String!
}

type LoginUserPayload implements MutationPayload {
  user: User!
  message: String!
}

input UpdateTodo {
  todoId: String!
  text: String!
  done: Boolean!
}

input DeleteTodos {
  ids: [ID!]!
}

type UpdatedTodoPayload implements MutationPayload {
  todo: Todo!
  message: String!
}

type DeleteTodoPayload implements MutationPayload {
  todoId: ID!
  message: String!
}

type DeleteTodosPayload implements MutationPayload {
  idsDeleted: [ID!]!
  idsNotDeleted: [ID!]!
  message: String!
}

type Mutation {
  createTodo(input: NewTodo!): Todo
  updateTodo(input: UpdateTodo!): UpdatedTodoPayload
  deleteTodo(id: ID!): DeleteTodoPayload
  deleteTodos(input: DeleteTodos!): DeleteTodosPayload

  createUser(input: NewUser!): CreateUserPayload
  LoginUser(input: NewLogin!): LoginUserPayload
}
