package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	//"learn_gqlgen/auth/entity"
	"learn_gqlgen/graph/model"
	entity_todo "learn_gqlgen/todo/entity"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	getNewTodo := &entity_todo.NewTodo{
		Text:   input.Text,
		UserID: input.UserID,
	}
	if r.TodoService == nil {
		return nil, fmt.Errorf("Service non initié !")
	}
	res, err := r.TodoService.AddTodo(ctx, getNewTodo)
	if err != nil {
		return nil, err
	}
	return &model.Todo{
		ID:        res.ID,
		Text:      res.Text,
		Done:      res.Done,
		CreatedAt: res.CreatedAt,
	}, nil
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, input model.UpdateTodo) (*model.UpdatedTodoPayload, error) {
	getUpdateTodo := &entity_todo.UpdateTodo{
		TodoID: input.TodoID,
		Text:   input.Text,
		Done:   input.Done,
	}
	updatedTodo, err := r.TodoService.UpdateTodo(ctx, getUpdateTodo)
	if err != nil {
		return nil, err
	}
	return &model.UpdatedTodoPayload{
		Todo: &model.Todo{
			ID:        updatedTodo.Todo.ID,
			Text:      updatedTodo.Todo.Text,
			Done:      updatedTodo.Todo.Done,
			CreatedAt: updatedTodo.Todo.CreatedAt,
			UpdatedAt: updatedTodo.Todo.UpdatedAt,
		},
		Message: updatedTodo.Message,
	}, nil
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, id string) (*model.DeleteTodoPayload, error) {
	result, err := r.TodoService.DeleteTodo(ctx, id)
	if err != nil {
		return nil, err
	}
	return &model.DeleteTodoPayload{
		TodoID:  result.ID,
		Message: result.Message,
	}, nil
}

// DeleteTodos is the resolver for the deleteTodos field.
func (r *mutationResolver) DeleteTodos(ctx context.Context, input model.DeleteTodos) (*model.DeleteTodosPayload, error) {
	ids, err := r.TodoService.DeleteTodos(ctx, input.Ids)
	if err != nil {
		return nil, err
	}
	return &model.DeleteTodosPayload{
		IdsDeleted:    ids.IDsDeleted,
		IdsNotDeleted: ids.IDsNotDeleted,
		Message:       ids.Message,
	}, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	fmt.Println("User infos : ", input)
	/**getNewUser := &entity.NewUser{
		Name: input.Name,
		Email: input.Email,
		Password: input.Password,
	}*/
	//user, err := r.AuthService.Create(ctx, getNewUser)
	/**if err != nil {
		return nil, err
	}*/
	return &model.User{}, nil
}

// GetTodo is the resolver for the getTodo field.
func (r *queryResolver) GetTodo(ctx context.Context, id string) (*model.Todo, error) {
	todo, err := r.TodoService.GetTodo(ctx, id)
	if err != nil {
		return nil, err
	}
	return &model.Todo{
		ID:        todo.ID,
		Text:      todo.Text,
		Done:      todo.Done,
		CreatedAt: todo.CreatedAt,
		UpdatedAt: todo.UpdatedAt,
	}, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	var todos []*model.Todo
	allTodos, err := r.TodoService.GetAllTodos(ctx)
	if err != nil {
		return nil, fmt.Errorf("Erreur lors de la récupération des todos.")
	}
	for _, todo := range allTodos {
		thisTodo := &model.Todo{
			ID:        todo.ID,
			Text:      todo.Text,
			Done:      todo.Done,
			CreatedAt: todo.CreatedAt,
			UpdatedAt: todo.UpdatedAt,
		}
		todos = append(todos, thisTodo)
	}
	return todos, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
