// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type MutationPayload interface {
	IsMutationPayload()
	GetMessage() string
}

type DeleteTodoPayload struct {
	TodoID  string `json:"todoId"`
	Message string `json:"message"`
}

func (DeleteTodoPayload) IsMutationPayload()      {}
func (this DeleteTodoPayload) GetMessage() string { return this.Message }

type DeleteTodos struct {
	Ids []string `json:"ids"`
}

type DeleteTodosPayload struct {
	IdsDeleted    []string `json:"idsDeleted"`
	IdsNotDeleted []string `json:"idsNotDeleted"`
	Message       string   `json:"message"`
}

func (DeleteTodosPayload) IsMutationPayload()      {}
func (this DeleteTodosPayload) GetMessage() string { return this.Message }

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Query struct {
}

type Todo struct {
	ID        string     `json:"id"`
	Text      string     `json:"text"`
	Done      bool       `json:"done"`
	User      *User      `json:"user"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type UpdateTodo struct {
	TodoID string `json:"todoId"`
	Text   string `json:"text"`
	Done   bool   `json:"done"`
}

type UpdatedTodoPayload struct {
	Todo    *Todo  `json:"todo"`
	Message string `json:"message"`
}

func (UpdatedTodoPayload) IsMutationPayload()      {}
func (this UpdatedTodoPayload) GetMessage() string { return this.Message }

type User struct {
	ID             string     `json:"id"`
	Name           string     `json:"name"`
	Email          string     `json:"email"`
	PasswordHashed string     `json:"passwordHashed"`
	CreatedAt      time.Time  `json:"createdAt"`
	UpdatedAt      *time.Time `json:"updatedAt,omitempty"`
}
