// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type UpdateTodo struct {
	TodoID string `json:"todoId"`
	Text   string `json:"text"`
	Done   bool   `json:"done"`
}

type UpdatedTodoPayload struct {
	Todo    *Todo  `json:"todo"`
	Message string `json:"message"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
